import { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'all', name: 'همه', icon: '🍽️', count: 20 },
  { id: 'burger', name: 'برگر', icon: '🍔', count: 6 },
  { id: 'pizza', name: 'پیتزا', icon: '🍕', count: 4 },
  { id: 'chicken', name: 'مرغ', icon: '🍗', count: 4 },
  { id: 'sandwich', name: 'ساندویچ', icon: '🥪', count: 3 },
  { id: 'drink', name: 'نوشیدنی', icon: '🥤', count: 4 },
  { id: 'dessert', name: 'دسر', icon: '🍰', count: 3 },
  { id: 'sides', name: 'پیش‌غذا', icon: '🍟', count: 4 },
];

export const products: Product[] = [
  {
    id: 1,
    name: 'برگر کلاسیک دوبل',
    description: 'دو لایه گوشت گریل شده با پنیر چدار، کاهو، گوجه و سس مخصوص',
    price: 185000,
    originalPrice: 220000,
    image: '🍔',
    category: 'burger',
    rating: 4.8,
    reviews: 234,
    isPopular: true,
    ingredients: ['گوشت گریل شده', 'پنیر چدار', 'کاهو', 'گوجه', 'پیاز', 'سس مخصوص'],
    calories: 650,
    prepTime: '15 دقیقه',
  },
  {
    id: 2,
    name: 'برگر زغالی ویژه',
    description: 'برگر گوشت گریل شده روی زغال با سس باربیکیو و قارچ',
    price: 210000,
    image: '🍔',
    category: 'burger',
    rating: 4.9,
    reviews: 189,
    isPopular: true,
    ingredients: ['گوشت گریل زغالی', 'سس باربیکیو', 'قارچ', 'پنیر گودا', 'پیاز حلقه‌ای'],
    calories: 720,
    prepTime: '20 دقیقه',
  },
  {
    id: 3,
    name: 'برگر تند آتشین',
    description: 'برگر با فلفل هالوپنو و سس تند مخصوص، مناسب عاشقان تندی',
    price: 195000,
    image: '🌶️',
    category: 'burger',
    rating: 4.6,
    reviews: 156,
    isSpicy: true,
    ingredients: ['گوشت گریل شده', 'فلفل هالوپنو', 'سس تند', 'پنیر پپری', 'کاهو'],
    calories: 580,
    prepTime: '15 دقیقه',
  },
  {
    id: 4,
    name: 'برگر مرغ کریسپی',
    description: 'فیله مرغ سوخاری با سس رنچ و کاهو تازه',
    price: 165000,
    image: '🍔',
    category: 'burger',
    rating: 4.7,
    reviews: 198,
    isNew: true,
    ingredients: ['فیله مرغ سوخاری', 'سس رنچ', 'کاهو', 'گوجه', 'خیارشور'],
    calories: 520,
    prepTime: '12 دقیقه',
  },
  {
    id: 5,
    name: 'پیتزا پپرونی',
    description: 'پیتزا با پپرونی تازه، پنیر موزارلا و سس گوجه خانگی',
    price: 245000,
    originalPrice: 280000,
    image: '🍕',
    category: 'pizza',
    rating: 4.9,
    reviews: 312,
    isPopular: true,
    ingredients: ['پپرونی', 'پنیر موزارلا', 'سس گوجه', 'فلفل دلمه‌ای', 'زیتون'],
    calories: 850,
    prepTime: '25 دقیقه',
  },
  {
    id: 6,
    name: 'پیتزا مارگاریتا',
    description: 'پیتزا کلاسیک ایتالیایی با ریحان تازه و پنیر موزارلا',
    price: 220000,
    image: '🍕',
    category: 'pizza',
    rating: 4.5,
    reviews: 145,
    ingredients: ['پنیر موزارلا', 'گوجه تازه', 'ریحان', 'روغن زیتون'],
    calories: 750,
    prepTime: '20 دقیقه',
  },
  {
    id: 7,
    name: 'پیتزا مخصوص شف',
    description: 'پیتزا با ترکیب گوشت، قارچ، فلفل و پنیر ویژه',
    price: 285000,
    image: '🍕',
    category: 'pizza',
    rating: 4.8,
    reviews: 267,
    isNew: true,
    ingredients: ['گوشت چرخ‌کرده', 'قارچ', 'فلفل دلمه‌ای', 'پنیر ویژه', 'ذرت'],
    calories: 920,
    prepTime: '30 دقیقه',
  },
  {
    id: 8,
    name: 'پیتزا چهار پنیر',
    description: 'ترکیب چهار نوع پنیر لذیذ روی خمیر دست‌ساز',
    price: 265000,
    image: '🧀',
    category: 'pizza',
    rating: 4.7,
    reviews: 178,
    ingredients: ['موزارلا', 'گودا', 'پارمزان', 'چدار', 'خمیر دست‌ساز'],
    calories: 880,
    prepTime: '25 دقیقه',
  },
  {
    id: 9,
    name: 'بال مرغ سوخاری',
    description: '8 عدد بال مرغ سوخاری کریسپی با سس مخصوص',
    price: 155000,
    image: '🍗',
    category: 'chicken',
    rating: 4.6,
    reviews: 289,
    isPopular: true,
    ingredients: ['بال مرغ', 'آرد سوخاری', 'ادویه مخصوص', 'سس'],
    calories: 480,
    prepTime: '18 دقیقه',
  },
  {
    id: 10,
    name: 'استریپ مرغ',
    description: '6 عدد تکه فیله مرغ سوخاری با سس عسل و خردل',
    price: 175000,
    image: '🍗',
    category: 'chicken',
    rating: 4.8,
    reviews: 201,
    ingredients: ['فیله مرغ', 'آرد سوخاری', 'سس عسل خردل', 'ادویه'],
    calories: 420,
    prepTime: '15 دقیقه',
  },
  {
    id: 11,
    name: 'ناگت مرغ',
    description: '12 عدد ناگت مرغ با سس‌های متنوع',
    price: 135000,
    image: '🍗',
    category: 'chicken',
    rating: 4.5,
    reviews: 167,
    ingredients: ['گوشت مرغ', 'آرد سوخاری', 'سس کچاپ', 'سس سیر'],
    calories: 380,
    prepTime: '12 دقیقه',
  },
  {
    id: 12,
    name: 'مرغ تند کره‌ای',
    description: 'مرغ سوخاری با سس تند کره‌ای و کنجد',
    price: 195000,
    image: '🍗',
    category: 'chicken',
    rating: 4.9,
    reviews: 345,
    isSpicy: true,
    isPopular: true,
    ingredients: ['مرغ سوخاری', 'سس گوجانگ', 'عسل', 'کنجد', 'سیر'],
    calories: 550,
    prepTime: '20 دقیقه',
  },
  {
    id: 13,
    name: 'ساندویچ کلاب',
    description: 'ساندویچ با مرغ گریل، بیکن، کاهو و گوجه',
    price: 145000,
    image: '🥪',
    category: 'sandwich',
    rating: 4.6,
    reviews: 134,
    ingredients: ['مرغ گریل', 'بیکن', 'کاهو', 'گوجه', 'سس مایو'],
    calories: 480,
    prepTime: '10 دقیقه',
  },
  {
    id: 14,
    name: 'ساندویچ فیله استیک',
    description: 'فیله استیک با قارچ، پنیر و سس مخصوص',
    price: 225000,
    image: '🥪',
    category: 'sandwich',
    rating: 4.8,
    reviews: 156,
    isNew: true,
    ingredients: ['فیله استیک', 'قارچ گریل', 'پنیر چدار', 'پیاز کاراملی'],
    calories: 620,
    prepTime: '18 دقیقه',
  },
  {
    id: 15,
    name: 'رپ مرغ',
    description: 'رپ با مرغ سوخاری، کاهو و سس سزار',
    price: 125000,
    image: '🌯',
    category: 'sandwich',
    rating: 4.4,
    reviews: 98,
    ingredients: ['تورتیلا', 'مرغ سوخاری', 'کاهو', 'سس سزار', 'پنیر'],
    calories: 390,
    prepTime: '8 دقیقه',
  },
  {
    id: 16,
    name: 'کوکاکولا',
    description: 'نوشابه کوکاکولا 330 میل',
    price: 25000,
    image: '🥤',
    category: 'drink',
    rating: 4.3,
    reviews: 567,
    calories: 140,
    prepTime: '1 دقیقه',
  },
  {
    id: 17,
    name: 'لیموناد تازه',
    description: 'لیموناد خانگی با نعنا و یخ',
    price: 45000,
    image: '🍋',
    category: 'drink',
    rating: 4.7,
    reviews: 234,
    isNew: true,
    ingredients: ['لیمو تازه', 'نعنا', 'شکر', 'یخ'],
    calories: 120,
    prepTime: '3 دقیقه',
  },
  {
    id: 18,
    name: 'میلک‌شیک شکلاتی',
    description: 'میلک‌شیک شکلاتی غلیظ با بستنی وانیلی',
    price: 65000,
    image: '🥛',
    category: 'drink',
    rating: 4.8,
    reviews: 189,
    isPopular: true,
    ingredients: ['شکلات', 'بستنی وانیلی', 'شیر', 'خامه'],
    calories: 380,
    prepTime: '5 دقیقه',
  },
  {
    id: 19,
    name: 'آب معدنی',
    description: 'آب معدنی 500 میل',
    price: 15000,
    image: '💧',
    category: 'drink',
    rating: 4.0,
    reviews: 890,
    calories: 0,
    prepTime: '1 دقیقه',
  },
  {
    id: 20,
    name: 'براونی شکلاتی',
    description: 'براونی شکلاتی گرم با سس شکلات و بستنی',
    price: 75000,
    image: '🍫',
    category: 'dessert',
    rating: 4.9,
    reviews: 278,
    isPopular: true,
    ingredients: ['شکلات تلخ', 'کره', 'تخم‌مرغ', 'آرد', 'بستنی'],
    calories: 450,
    prepTime: '10 دقیقه',
  },
  {
    id: 21,
    name: 'چیزکیک توت‌فرنگی',
    description: 'چیزکیک نیویورکی با سس توت‌فرنگی تازه',
    price: 85000,
    image: '🍰',
    category: 'dessert',
    rating: 4.8,
    reviews: 156,
    ingredients: ['پنیر خامه‌ای', 'بیسکویت', 'توت‌فرنگی', 'شکر'],
    calories: 380,
    prepTime: '5 دقیقه',
  },
  {
    id: 22,
    name: 'آیس‌کریم سه‌گانه',
    description: 'سه اسکوپ بستنی با طعم‌های مختلف و تاپینگ',
    price: 55000,
    image: '🍨',
    category: 'dessert',
    rating: 4.6,
    reviews: 198,
    ingredients: ['بستنی وانیلی', 'بستنی شکلاتی', 'بستنی توت‌فرنگی', 'تاپینگ'],
    calories: 320,
    prepTime: '3 دقیقه',
  },
  {
    id: 23,
    name: 'سیب‌زمینی سرخ‌کرده',
    description: 'سیب‌زمینی سرخ‌کرده کریسپی با سس کچاپ',
    price: 65000,
    image: '🍟',
    category: 'sides',
    rating: 4.5,
    reviews: 456,
    isPopular: true,
    ingredients: ['سیب‌زمینی', 'روغن', 'نمک', 'سس کچاپ'],
    calories: 350,
    prepTime: '10 دقیقه',
  },
  {
    id: 24,
    name: 'حلقه‌های پیاز',
    description: 'حلقه‌های پیاز سوخاری کریسپی',
    price: 55000,
    image: '🧅',
    category: 'sides',
    rating: 4.4,
    reviews: 123,
    ingredients: ['پیاز', 'آرد سوخاری', 'ادویه', 'سس رنچ'],
    calories: 280,
    prepTime: '8 دقیقه',
  },
  {
    id: 25,
    name: 'سالاد سزار',
    description: 'سالاد سزار با مرغ گریل و سس مخصوص',
    price: 85000,
    image: '🥗',
    category: 'sides',
    rating: 4.6,
    reviews: 167,
    ingredients: ['کاهو رومی', 'مرغ گریل', 'پنیر پارمزان', 'نان تست', 'سس سزار'],
    calories: 250,
    prepTime: '7 دقیقه',
  },
  {
    id: 26,
    name: 'سوپ قارچ',
    description: 'سوپ قارچ خامه‌ای با نان سیر',
    price: 55000,
    image: '🍲',
    category: 'sides',
    rating: 4.3,
    reviews: 89,
    ingredients: ['قارچ', 'خامه', 'کره', 'نان سیر'],
    calories: 180,
    prepTime: '12 دقیقه',
  },
];
