import { Product, Category } from './types';

// Images
const IMG = {
  burger: 'https://image.qwenlm.ai/generated-images/d762ddf7-aa3a-4e51-a165-8a7d0bfad476/_result.png',
  pizza: 'https://image.qwenlm.ai/generated-images/c2908543-bd68-47c7-b499-3fc20e6e5b1a/_result.png',
  chicken: 'https://image.qwenlm.ai/generated-images/d3c69ee6-95a3-40ea-8e13-c500e201afab/_result.png',
  fries: 'https://image.qwenlm.ai/generated-images/543b5d21-2987-4ff7-a397-1efaffb0f0f7/_result.png',
  hero: 'https://image.qwenlm.ai/generated-images/22b4196c-e406-4409-bfe7-6528b9412eb1/_result.png',
  sandwich: 'https://image.qwenlm.ai/generated-images/cb620db5-53d7-4cc5-8a60-c852317e3786/_result.png',
  milkshake: 'https://image.qwenlm.ai/generated-images/a3af1bca-9706-4c21-9a6d-17600fa30909/_result.png',
  brownie: 'https://image.qwenlm.ai/generated-images/6bc74be7-f083-4cbd-b611-0c8c81901ab2/_result.png',
  onion: 'https://image.qwenlm.ai/generated-images/ae556b00-7d65-47dd-945e-92ddc4e14175/_result.png',
  salad: 'https://image.qwenlm.ai/generated-images/2c994515-f673-4b37-893e-7470ddbaf1c3/_result.png',
};

export const categories: Category[] = [
  { id: 'all', name: 'همه', image: IMG.burger, count: 12 },
  { id: 'burger', name: 'برگر', image: IMG.burger, count: 3 },
  { id: 'pizza', name: 'پیتزا', image: IMG.pizza, count: 2 },
  { id: 'chicken', name: 'مرغ', image: IMG.chicken, count: 2 },
  { id: 'sandwich', name: 'ساندویچ', image: IMG.sandwich, count: 1 },
  { id: 'sides', name: 'پیش‌غذا', image: IMG.fries, count: 2 },
  { id: 'drink', name: 'نوشیدنی', image: IMG.milkshake, count: 1 },
  { id: 'dessert', name: 'دسر', image: IMG.brownie, count: 1 },
];

export const products: Product[] = [
  {
    id: 1,
    name: 'دبل چیزبرگر کلاسیک',
    description: 'دو لایه گوشت تازه ۱۸۰ گرمی با پنیر چدار ذوب‌شده، کاهو آیسبرگ، گوجه و سس مخصوص شف',
    price: 385000,
    originalPrice: 450000,
    image: IMG.burger,
    category: 'burger',
    rating: 4.9,
    reviews: 2847,
    isPopular: true,
    ingredients: ['گوشت تازه ۳۶۰ گرم', 'پنیر چدار', 'کاهو آیسبرگ', 'گوجه', 'پیاز کاراملی', 'سس مخصوص'],
    calories: 890,
    prepTime: '۱۵ دقیقه',
  },
  {
    id: 2,
    name: 'موشروم برگر پریمیوم',
    description: 'برگر ۲۰۰ گرمی با قارچ پورتوبلو گریل‌شده، پنیر سوئیسی و سس ترافل',
    price: 425000,
    image: IMG.burger,
    category: 'burger',
    rating: 4.8,
    reviews: 1567,
    isNew: true,
    ingredients: ['گوشت ۲۰۰ گرم', 'قارچ پورتوبلو', 'پنیر سوئیسی', 'پیاز سرخ‌شده', 'سس ترافل'],
    calories: 780,
    prepTime: '۱۸ دقیقه',
  },
  {
    id: 3,
    name: 'اسپایسی چیکن برگر',
    description: 'فیله مرغ سوخاری کریسپی با سس اسپایسی مخصوص و کولسلو',
    price: 295000,
    image: IMG.burger,
    category: 'burger',
    rating: 4.7,
    reviews: 987,
    isSpicy: true,
    ingredients: ['فیله مرغ سوخاری', 'سس اسپایسی', 'کولسلو', 'خیارشور', 'کاهو'],
    calories: 650,
    prepTime: '۱۲ دقیقه',
  },
  {
    id: 4,
    name: 'پیتزا پپرونی ایتالیایی',
    description: 'خمیر دست‌ساز ناپلی با پپرونی اصل ایتالیا، پنیر موزارلای تازه و ریحان',
    price: 445000,
    originalPrice: 520000,
    image: IMG.pizza,
    category: 'pizza',
    rating: 4.9,
    reviews: 3421,
    isPopular: true,
    ingredients: ['خمیر دست‌ساز ناپلی', 'پپرونی ایتالیایی', 'موزارلای تازه', 'سس گوجه خانگی', 'ریحان'],
    calories: 920,
    prepTime: '۲۰ دقیقه',
  },
  {
    id: 5,
    name: 'پیتزا مارگاریتا اصیل',
    description: 'پیتزا اصیل ناپلی با گوجه سن‌مارزانو و موزارلای بوفالو',
    price: 385000,
    image: IMG.pizza,
    category: 'pizza',
    rating: 4.8,
    reviews: 1876,
    ingredients: ['خمیر ناپلی', 'گوجه سن‌مارزانو', 'موزارلای بوفالو', 'ریحان تازه', 'روغن زیتون فرابکر'],
    calories: 850,
    prepTime: '۱۸ دقیقه',
  },
  {
    id: 6,
    name: 'چیکن استریپس کریسپی',
    description: '۸ تکه استریپ فیله مرغ با سوخاری کریسپی طلایی و سس عسل‌خردل',
    price: 285000,
    image: IMG.chicken,
    category: 'chicken',
    rating: 4.8,
    reviews: 2156,
    isPopular: true,
    ingredients: ['فیله مرغ تازه', 'سوخاری مخصوص ۱۲ قلم', 'سس عسل خردل', 'ادویه'],
    calories: 580,
    prepTime: '۱۵ دقیقه',
  },
  {
    id: 7,
    name: 'بال مرغ بوفالو',
    description: '۱۰ عدد بال مرغ با سس بوفالوی اصل و سس رنچ خانگی',
    price: 325000,
    image: IMG.chicken,
    category: 'chicken',
    rating: 4.7,
    reviews: 1432,
    isSpicy: true,
    ingredients: ['بال مرغ تازه', 'سس بوفالو', 'کره', 'سس رنچ خانگی', 'کرفس'],
    calories: 720,
    prepTime: '۱۸ دقیقه',
  },
  {
    id: 8,
    name: 'استیک ساندویچ پریمیوم',
    description: 'استیک ریب‌آی ۲۰۰ گرمی با قارچ گریل، پنیر پروولون و پیاز کاراملی',
    price: 485000,
    image: IMG.sandwich,
    category: 'sandwich',
    rating: 4.9,
    reviews: 876,
    isNew: true,
    ingredients: ['استیک ریب‌آی ۲۰۰ گرم', 'قارچ گریل', 'پنیر پروولون', 'پیاز کاراملی', 'نان چاباتا'],
    calories: 820,
    prepTime: '۲۰ دقیقه',
  },
  {
    id: 9,
    name: 'سیب‌زمینی سرخ‌کرده ویژه',
    description: 'سیب‌زمینی تازه سرخ‌شده با نمک دریا و ادویه مخصوص',
    price: 125000,
    image: IMG.fries,
    category: 'sides',
    rating: 4.6,
    reviews: 4532,
    ingredients: ['سیب‌زمینی تازه', 'نمک دریا', 'ادویه مخصوص', 'سس کچاپ'],
    calories: 380,
    prepTime: '۱۰ دقیقه',
  },
  {
    id: 10,
    name: 'حلقه‌های پیاز کریسپی',
    description: 'حلقه‌های پیاز با سوخاری پانکو و سس رنچ خانگی',
    price: 165000,
    image: IMG.onion,
    category: 'sides',
    rating: 4.5,
    reviews: 1234,
    ingredients: ['پیاز درشت', 'سوخاری پانکو', 'ادویه مخصوص', 'سس رنچ خانگی'],
    calories: 320,
    prepTime: '۱۰ دقیقه',
  },
  {
    id: 11,
    name: 'میلک‌شیک شکلات بلژیکی',
    description: 'میلک‌شیک غلیظ با شکلات بلژیکی کالیبو و بستنی وانیلی',
    price: 145000,
    image: IMG.milkshake,
    category: 'drink',
    rating: 4.9,
    reviews: 2876,
    isPopular: true,
    ingredients: ['شکلات بلژیکی کالیبو', 'بستنی وانیلی', 'شیر تازه', 'خامه فرم‌شده'],
    calories: 480,
    prepTime: '۵ دقیقه',
  },
  {
    id: 12,
    name: 'براونی لاوا شکلاتی',
    description: 'براونی شکلاتی گرم با مغز مذاب، بستنی وانیلی و سس شکلات',
    price: 185000,
    image: IMG.brownie,
    category: 'dessert',
    rating: 4.9,
    reviews: 1987,
    isNew: true,
    ingredients: ['شکلات تلخ ۷۰٪', 'کره فرانسوی', 'تخم‌مرغ محلی', 'بستنی وانیلی', 'سس شکلات'],
    calories: 520,
    prepTime: '۱۰ دقیقه',
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'علی محمدی',
    role: 'مشتری وفادار',
    text: 'بهترین برگری که تا حالا خوردم. کیفیت مواد اولیه واقعاً فوق‌العاده‌ست و طعم‌ها بی‌نظیرن. حتماً امتحان کنید.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
  },
  {
    id: 2,
    name: 'سارا احمدی',
    role: 'بلاگر غذا',
    text: 'پیتزاشون واقعاً حرف نداره. خمیر دست‌ساز و مواد تازه. سرویس‌دهی هم عالیه. یکی از بهترین‌های تهران.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
  },
  {
    id: 3,
    name: 'رضا کریمی',
    role: 'مشتری دائمی',
    text: 'سرویس‌دهی سریع و بسته‌بندی عالی. غذا داغ و تازه به دستم رسید. ممنون از تیم حرفه‌ای برگرلند.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
  },
];

export const IMG_HERO = IMG.hero;
